// Regenerate and verify src/patchsize.ts — the rhomb count of every patch and generation.
//
//   node tools/patchsize.mjs          verify the table against the generator
//   node tools/patchsize.mjs --write  regenerate it
//
// The table exists so a page can populate its generation dropdown without running the
// deflation to find out how big each choice would be. Counts are deterministic, so a
// stored table is honest — but it can drift, which is what the verify mode is for.

import { readFileSync, writeFileSync } from "node:fs";
import { generatePatch, allRhombs, seedTypes } from "../dist/geometry.js";
import { triacontahedra } from "../dist/centers.js";
import { properBalls } from "../dist/packing.js";

// Ball counts are measured only where the patch is small enough to do it quickly; past
// this the packing page cannot draw a cutaway anyway, so -1 stands for "not measured,
// and too large regardless".
const BALL_CEILING = 15000;

const CODES = ["Pe5", "Pe3", "Pe1", "St5", "St3", "St1", "Deca", "Sun", "Star"];
const MAX_GEN = 6;

const counts = {};
const balls = {};
for (const code of CODES) {
    const i = seedTypes.findIndex((s) => s.label === code);
    counts[code] = [];
    balls[code] = [];
    for (let g = 1; g <= MAX_GEN; g++) {
        const quiet = console.log;
        console.log = () => {};
        generatePatch(i, true, g);
        const n = allRhombs.length;
        const b = n > 0 && n <= BALL_CEILING ? properBalls(triacontahedra()).length : -1;
        console.log = quiet;
        counts[code].push(n);
        balls[code].push(b);
    }
}

const body = CODES.map((c) => `    ${c}: [${counts[c].join(", ")}],`).join("\n");
const ballBody = CODES.map((c) => `    ${c}: [${balls[c].join(", ")}],`).join("\n");
const file = `// Rhomb count of every patch at every generation, 1 through ${MAX_GEN}.
//
// Generated by \`tools/patchsize.mjs\`, which also verifies it against the generator.
// A page needs these before it draws anything — to fill a generation dropdown it has to
// know how big each choice would be, and running the deflation to find out would cost
// exactly what the dropdown is trying to avoid.
//
// A zero means the patch does not exist at that generation: the three star seeds have no
// generation 1, since a star, boat or diamond is not produced until the first deflation.

export const MAX_GENERATION = ${MAX_GEN};

export const PATCH_SIZE: Record<string, number[]> = {
${body}
};

/**
 * Proper triacontahedra in the same patch — the balls of the packing.
 *
 * \`-1\` means not measured: the patch is past ${BALL_CEILING.toLocaleString()} rhombs, which is far past
 * what the cutaway can draw anyway, so the exact number would not change any decision.
 */
export const PATCH_BALLS: Record<string, number[]> = {
${ballBody}
};

/** Rhombs in a patch, or 0 if it does not exist. */
export function patchSize(code: string, gen: number): number {
    return PATCH_SIZE[code]?.[gen - 1] ?? 0;
}

/** Balls in the same patch, or -1 where it was too large to measure. */
export function patchBalls(code: string, gen: number): number {
    return PATCH_BALLS[code]?.[gen - 1] ?? 0;
}
`;

if (process.argv.includes("--write")) {
    writeFileSync("src/patchsize.ts", file);
    console.log("wrote src/patchsize.ts");
} else {
    const on_disk = readFileSync("src/patchsize.ts", "utf8");
    if (on_disk !== file) {
        console.log("  ✗ src/patchsize.ts is out of date — run with --write");
        process.exit(1);
    }
    console.log(`patch sizes verified against the generator: ${CODES.length} patches x ${MAX_GEN} generations`);
}
